import {describe,expect,it} from 'vitest';
import {attackKind,damage,heal,initialEncounter,resetTransient,stepEncounter} from './encounter';
const player={x:0,y:1,z:0},velocity={x:0,y:0,z:0};
describe('deterministic encounters',()=>{
 it('recognizes only movement attacks and defeats a small enemy from above',()=>{expect(attackKind('idle',velocity)).toBe('none');expect(attackKind('fall',{...velocity,y:-2})).toBe('stomp');let s=initialEncounter();s.enemies[0].position={x:0,y:0,z:0};const r=stepEncounter(s,{player:{...player,y:1},playerVelocity:{...velocity,y:-2},playerMove:'fall',phase:'beacons'},1/60);expect(r.enemyDefeated).toBe('gale-runner');expect(r.state.enemies[0].mode).toBe('defeated')});
 it('telegraphs a charger before deterministic motion',()=>{let s=initialEncounter();s.enemies[0].position={x:0,y:0,z:0};s.enemies[0].home={x:0,y:0,z:0};s=stepEncounter(s,{player:{x:5,y:0,z:0},playerVelocity:velocity,playerMove:'idle',phase:'beacons'},.1).state;expect(s.enemies[0].mode).toBe('telegraph');s=stepEncounter(s,{player:{x:5,y:0,z:0},playerVelocity:velocity,playerMove:'idle',phase:'beacons'},.8).state;expect(s.enemies[0].mode).toBe('attack')});
 it('winds up, fires, moves, and lands a spitter pellet',()=>{let s=initialEncounter();const spitter=s.enemies[1];spitter.position={x:0,y:0,z:0};spitter.home={...spitter.position};spitter.timer=0;s=stepEncounter(s,{player:{x:6,y:.65,z:0},playerVelocity:velocity,playerMove:'idle',phase:'beacons'},.01).state;expect(s.enemies[1].mode).toBe('telegraph');s=stepEncounter(s,{player:{x:6,y:.65,z:0},playerVelocity:velocity,playerMove:'idle',phase:'beacons'},.56).state;expect(s.projectiles).toHaveLength(1);const x=s.projectiles[0].position.x;s=stepEncounter(s,{player:{x:6,y:.65,z:0},playerVelocity:velocity,playerMove:'idle',phase:'beacons'},.25).state;expect(s.projectiles[0].position.x).toBeGreaterThan(x);const result=stepEncounter(s,{player:{x:2.1,y:1.1,z:0},playerVelocity:velocity,playerMove:'idle',phase:'beacons'},.25);expect(result.damage?.amount).toBe(1)});
 it('heals damaged players without exceeding maximum health or consuming a full-health pickup',()=>{const damaged=damage(initialEncounter(),2);expect(heal(damaged,1).health).toBe(5);expect(heal(damaged,20).health).toBe(6);const full=initialEncounter();expect(heal(full,2)).toBe(full)});
 it('applies invulnerability and restores health while resetting summit hits',()=>{let s=damage(initialEncounter(),2);expect(damage(s,2).health).toBe(4);s.guardian.hits=2;expect(resetTransient(s,true)).toMatchObject({health:6,guardian:{hits:0}})});
 it('allows at most one core hit per exposure and finishes on three',()=>{let s=initialEncounter();for(let hit=1;hit<=3;hit++){s.guardian.mode='exposed';s.guardian.timer=3;s.guardian.position={x:0,y:1,z:0};s.guardian.hitThisExposure=false;let r=stepEncounter(s,{player,playerVelocity:{...velocity,y:-2},playerMove:'fall',phase:'summit'},1/60);expect(r.guardianHit).toBe(hit);s=r.state;const duplicate=stepEncounter(s,{player,playerVelocity:{...velocity,y:-2},playerMove:'fall',phase:'summit'},1/60);expect(duplicate.guardianHit).toBeUndefined();if(hit<3)s=duplicate.state}expect(s.guardian.mode).toBe('defeated')});
});
