import * as THREE from 'three';
import { InputNormalizer, type FrameInput } from './input';
import { initialPlayer, stepPlayer, type PlayerState } from './player';
import type { Settings } from './settings';

export class Game {
  readonly input=new InputNormalizer(); private renderer:THREE.WebGLRenderer; private scene=new THREE.Scene(); private camera=new THREE.PerspectiveCamera(58,1,.1,100);
  private hero:THREE.Group; private state:PlayerState=initialPlayer(); private accumulator=0; private last=0; private running=false; private yaw=0; private pitch=.45; private distance=8;
  constructor(private host:HTMLElement, private settings:Settings, private onPause:()=>void){
    this.renderer=new THREE.WebGLRenderer({antialias:true}); this.renderer.setPixelRatio(Math.min(devicePixelRatio,2)); this.renderer.shadowMap.enabled=true; host.prepend(this.renderer.domElement);
    this.scene.background=new THREE.Color('#8bc7cf'); this.scene.fog=new THREE.Fog('#8bc7cf',22,55);
    this.scene.add(new THREE.HemisphereLight('#fff3ca','#305968',2.2)); const sun=new THREE.DirectionalLight('#fff0b0',2.8);sun.position.set(-8,15,7);sun.castShadow=true;this.scene.add(sun);
    const shelf=new THREE.Mesh(new THREE.CylinderGeometry(16,14,1.5,9),new THREE.MeshStandardMaterial({color:'#d2ad58',roughness:.95}));shelf.position.y=-.75;shelf.receiveShadow=true;this.scene.add(shelf);
    for(let i=0;i<10;i++){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.5+(i%3)*.25,0),new THREE.MeshStandardMaterial({color:i%2?'#d9d2b1':'#a9c6b5'}));rock.position.set(Math.sin(i*2.3)*(6+i%5),.3,Math.cos(i*1.7)*(5+i%4));rock.scale.y=1.4;rock.castShadow=true;this.scene.add(rock);}
    this.hero=this.makeHero();this.scene.add(this.hero);this.bind();this.resize();
  }
  start(){this.running=true;this.last=performance.now();requestAnimationFrame(this.loop);}
  stop(){this.running=false;this.input.clearAll();}
  resume(){if(!this.running)this.start();}
  updateSettings(s:Settings){this.settings=s;}
  private makeHero(){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:'#f5e7a8',flatShading:true}),accent=new THREE.MeshStandardMaterial({color:'#247986',flatShading:true});const body=new THREE.Mesh(new THREE.OctahedronGeometry(.55,1),mat);body.position.y=.65;const head=new THREE.Mesh(new THREE.DodecahedronGeometry(.4,0),accent);head.position.y=1.45;const wing=new THREE.Mesh(new THREE.ConeGeometry(.28,.8,3),accent);wing.rotation.z=Math.PI/2;wing.position.set(0,.8,.45);g.add(body,head,wing);g.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});return g;}
  private loop=(now:number)=>{if(!this.running)return;const elapsed=Math.min(.1,(now-this.last)/1000);this.last=now;this.accumulator+=elapsed;const frame=this.poll();this.orbit(frame);while(this.accumulator>=1/60){this.state=stepPlayer(this.state,{move:frame.move,jumpPressed:frame.pressed.has('jump'),run:frame.held.run,cameraYaw:this.yaw,assist:this.settings.assist},1/60);this.accumulator-=1/60;frame.pressed.delete('jump');}this.hero.position.set(this.state.position.x,this.state.position.y-.8,this.state.position.z);this.hero.rotation.y=this.state.facing;this.placeCamera();this.renderer.render(this.scene,this.camera);requestAnimationFrame(this.loop)};
  private poll(){const pads=navigator.getGamepads?.()??[];const p=pads[0];if(p){this.input.setMove('gamepad',{x:dead(p.axes[0]),y:dead(p.axes[1])});this.input.setCamera('gamepad',{x:dead(p.axes[2]),y:dead(p.axes[3])},performance.now());this.input.addZoom(((p.buttons[7]?.value??0)-(p.buttons[6]?.value??0))*3);this.input.setButton('gamepad','jump',!!p.buttons[this.settings.gamepad.jump]?.pressed);this.input.setButton('gamepad','run',!!p.buttons[this.settings.gamepad.run]?.pressed);this.input.setButton('gamepad','recenter',!!p.buttons[this.settings.gamepad.recenter]?.pressed);this.input.setButton('gamepad','pause',!!p.buttons[this.settings.gamepad.pause]?.pressed);}const f=this.input.sample();if(f.pressed.has('pause'))this.onPause();return f;}
  private orbit(f:FrameInput){if(f.pressed.has('recenter'))this.yaw=this.state.facing+Math.PI;const scale=.025*this.settings.sensitivity;this.yaw-=f.camera.x*scale;this.pitch=Math.max(.15,Math.min(1.15,this.pitch+f.camera.y*scale*(this.settings.invertY?-1:1)));this.distance=Math.max(4,Math.min(12,this.distance+f.zoom*.008));}
  private placeCamera(){const target=new THREE.Vector3(this.state.position.x,this.state.position.y+.8,this.state.position.z);const dir=new THREE.Vector3(Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),Math.cos(this.yaw)*Math.cos(this.pitch));let d=this.distance;const edge=14-Math.hypot(target.x,target.z);if(edge<2)d=Math.max(3,d-(2-edge)*1.5);this.camera.position.copy(target).addScaledVector(dir,d);this.camera.lookAt(target);}
  private bind(){const keys=new Set<string>();const sync=()=>{const left=keys.has('KeyA')||keys.has('ArrowLeft'),right=keys.has('KeyD')||keys.has('ArrowRight'),up=keys.has('KeyW')||keys.has('ArrowUp'),down=keys.has('KeyS')||keys.has('ArrowDown');this.input.setMove('keyboard',{x:Number(right)-Number(left),y:Number(down)-Number(up)});for(const a of ['jump','run','recenter','pause'] as const)this.input.setButton('keyboard',a,keys.has(this.settings.keyboard[a]));};addEventListener('keydown',e=>{keys.add(e.code);sync();if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>{keys.delete(e.code);sync()});let drag=false,px=0,py=0;this.renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'){drag=true;px=e.clientX;py=e.clientY;this.renderer.domElement.setPointerCapture(e.pointerId)}});this.renderer.domElement.addEventListener('pointermove',e=>{if(drag){this.input.setCamera('mouse',{x:e.clientX-px,y:e.clientY-py});px=e.clientX;py=e.clientY}});this.renderer.domElement.addEventListener('pointerup',()=>drag=false);this.renderer.domElement.addEventListener('wheel',e=>{this.input.addZoom(e.deltaY);e.preventDefault()},{passive:false});addEventListener('gamepaddisconnected',()=>this.input.clearSource('gamepad'));addEventListener('resize',()=>this.resize());}
  resize(){const w=this.host.clientWidth,h=this.host.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
}
const dead=(v=0)=>Math.abs(v)<.16?0:v;
