import {describe,expect,it} from 'vitest';import {initialPlayer,stepPlayer,type PlayerState,type PlayerWorld} from './player';
const flat:PlayerWorld={ground:()=>({y:.8,normal:{x:0,y:1,z:0}}),bounds:{minX:-99,maxX:99,minZ:-99,maxZ:99,voidY:-20}};
const input=(o:Partial<Parameters<typeof stepPlayer>[1]>={})=>({move:{x:0,y:0},jumpPressed:false,run:false,cameraYaw:0,...o});
const tick=(s:PlayerState,n:number,i:Parameters<typeof stepPlayer>[1],w=flat)=>{for(let k=0;k<n;k++)s=stepPlayer(s,i,1/60,w);return s};
describe('deterministic traversal simulation',()=>{
 it('accelerates analog input, turns, and skids deterministically',()=>{const run=()=>tick(initialPlayer(),30,input({move:{x:.5,y:-.5},run:true}));expect(run()).toEqual(run());expect(Math.hypot(run().velocity.x,run().velocity.z)).toBeGreaterThan(4);let s=run();s=stepPlayer(s,input({move:{x:-.7,y:.7},run:true}),1/60,flat);expect(s.state).toBe('skid')});
 it('supports single, double, and timed triple jumps',()=>{let s=initialPlayer();const heights:number[]=[];for(let chain=0;chain<3;chain++){s=stepPlayer(s,input({jumpPressed:true}),1/60,flat);heights.push(s.velocity.y);s=tick(s,45,input(),flat)}expect(heights[1]).toBeGreaterThan(heights[0]);expect(heights[2]).toBeGreaterThan(heights[1])});
 it('resolves long jump, backflip, side flip, dive, and ground pound',()=>{let moving=initialPlayer();moving.velocity.z=-6;let s=stepPlayer(moving,input({move:{x:0,y:-1},crouch:true,jumpPressed:true}),1/60,flat);expect(Math.hypot(s.velocity.x,s.velocity.z)).toBeGreaterThan(10);let back=stepPlayer(initialPlayer(),input({crouch:true,jumpPressed:true}),1/60,flat);expect(back.velocity.y).toBeGreaterThan(10);let side=initialPlayer();side.velocity.z=5;side=stepPlayer(side,input({move:{x:0,y:-1},jumpPressed:true}),1/60,flat);expect(side.velocity.y).toBeGreaterThan(9);const air={...initialPlayer(),grounded:false,state:'fall' as const,position:{x:0,y:3,z:0},velocity:{x:0,y:-1,z:5}};expect(stepPlayer(air,input({divePressed:true}),1/60,flat).state).toBe('dive');expect(stepPlayer(air,input({crouchPressed:true}),1/60,flat).state).toBe('groundPound')});
 it('wall kicks and grabs/climbs eligible ledges',()=>{const wall:PlayerWorld={...flat,wall:()=>({normal:{x:-1,y:0,z:0}})};let s={...initialPlayer(),grounded:false,position:{x:2,y:3,z:0},velocity:{x:3,y:-1,z:0},state:'fall' as const};s=stepPlayer(s,input({jumpPressed:true}),1/60,wall);expect(s.velocity.x).toBeLessThan(0);const ledge:PlayerWorld={...flat,wall:()=>({normal:{x:1,y:0,z:0},ledgeY:4})};s={...s,position:{x:2,y:3,z:0},velocity:{x:1,y:-1,z:0},state:'fall',grounded:false};s=stepPlayer(s,input(),1/60,ledge);expect(s.state).toBe('hang');s=stepPlayer(s,input({jumpPressed:true}),1/60,ledge);expect(s.state).toBe('climb')});
 it('slides steep slopes, carries platforms, and enters landing recovery',()=>{const steep:PlayerWorld={ground:()=>({y:.8,normal:{x:.8,y:.6,z:0}})};let s=stepPlayer({...initialPlayer(),position:{x:0,y:1,z:0},grounded:false,velocity:{x:0,y:-2,z:0}},input(),1/60,steep);expect(s.state).toBe('slide');const moving:PlayerWorld={ground:()=>({y:.8,normal:{x:0,y:1,z:0},platform:'ferry',velocity:{x:2,y:0,z:0}})};s=stepPlayer(initialPlayer(),input(),1/60,moving);expect(s.position.x).toBeGreaterThan(0);s={...initialPlayer(),position:{x:0,y:1,z:0},grounded:false,velocity:{x:0,y:-15,z:0},fallPeak:12};s=stepPlayer(s,input(),1/60,flat);expect(s.state).toBe('hurt')});
 it('honors coyote and assist windows, and recovers from void',()=>{let s={...initialPlayer(),grounded:false,coyote:.08,position:{x:0,y:2,z:0}};s=stepPlayer(s,input({jumpPressed:true}),1/60,flat);expect(s.velocity.y).toBeGreaterThan(0);let assist={...initialPlayer(),grounded:false,coyote:.2,position:{x:0,y:2,z:0}};assist=tick(assist,8,input({assist:true}),flat);assist=stepPlayer(assist,input({jumpPressed:true,assist:true}),1/60,flat);expect(assist.velocity.y).toBeGreaterThan(0);const fallen={...initialPlayer(),grounded:false,position:{x:0,y:-30,z:0},state:'fall' as const};expect(stepPlayer(fallen,input(),1/60,flat).state).toBe('recover')});
});
